### ISSUE TITLE
Chyba  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by HonzaKr** [kukulich/home-assistant-aladin-online#2]
Dobrý den,
od 28.10 se v aplikaci objedvuje následující chyba:

Tato chyba pochází z vlastní integrace.

Logger: custom_components.aladin_online
Source: custom_components/aladin_online/aladin_online.py:127
Integration: Aladin online (Czech Republic) (documentation, issues)
First occurred: 15:37:02 (1 occurrences)
Last logged: 15:37:02

Unexpected error fetching aladin_online data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/aladin_online/aladin_online.py", line 127, in update
    data_time = AladinOnlineCoordinator._format_datetime(self._data[DATA_TIME])
TypeError: 'NoneType' object is not subscriptable

Dík jk

**Comment by kukulich** [comment]
Nefunguje zdroj: https://aladinonline.androworks.org/
